server:
  port: 9020

spring:
  application:
    name: platform-registry-center

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    #        register-with-eureka: ${EUREKA_HA:false}
    fetch-registry: ${EUREKA_HA:false}
    serviceUrl:
      defaultZone: ${REGISTRY_CENTER_URI:http://localhost:${server.port}/eureka/}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000


#security:
#    basic:
#        enabled: false
#    user:
#        name: user
#        password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"